#############################
### kafka相关配置
[Kafka]
topic  = "intercept"
num    = 10
thread = 20
addr   = "192.168.1.1:9092"
on     = false
#############################
[Other]
### 节点信息
local  = "127.0.0.1"
### 日志等级
debug = 10
### 虚拟机个数
vmnum = 5
